# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P1_Ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(160, 210, 235);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar.setGeometry(QtCore.QRect(100, 210, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_agregar.setFont(font)
        self.btn_agregar.setStyleSheet("background-color: rgb(193, 255, 126);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 127);\n"
"border-radius:20px;\n"
"border: 4px solid white;\n"
"")
        self.btn_agregar.setObjectName("btn_agregar")
        self.txt_calificacion = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_calificacion.setGeometry(QtCore.QRect(340, 110, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txt_calificacion.setFont(font)
        self.txt_calificacion.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 4px solid green;\n"
"")
        self.txt_calificacion.setText("")
        self.txt_calificacion.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_calificacion.setObjectName("txt_calificacion")
        self.txt_resultado = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_resultado.setGeometry(QtCore.QRect(360, 390, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txt_resultado.setFont(font)
        self.txt_resultado.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 4px solid green;")
        self.txt_resultado.setText("")
        self.txt_resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_resultado.setObjectName("txt_resultado")
        self.btn_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calcular.setGeometry(QtCore.QRect(360, 210, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_calcular.setFont(font)
        self.btn_calcular.setStyleSheet("background-color: rgb(193, 255, 126);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 127);\n"
"border-radius:20px;\n"
"border: 4px solid white;\n"
"")
        self.btn_calcular.setObjectName("btn_calcular")
        self.btn_agregar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar_2.setGeometry(QtCore.QRect(90, 90, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_agregar_2.setFont(font)
        self.btn_agregar_2.setStyleSheet("background-color: rgb(193, 255, 126);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 127);\n"
"border-radius:20px;\n"
"")
        self.btn_agregar_2.setObjectName("btn_agregar_2")
        self.btn_agregar_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar_3.setGeometry(QtCore.QRect(100, 370, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_agregar_3.setFont(font)
        self.btn_agregar_3.setStyleSheet("background-color: rgb(193, 255, 126);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 127);\n"
"border-radius:20px;\n"
"")
        self.btn_agregar_3.setObjectName("btn_agregar_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_agregar.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt;\">AGREGAR</span></p></body></html>"))
        self.btn_agregar.setText(_translate("MainWindow", "AGREGAR"))
        self.btn_calcular.setText(_translate("MainWindow", "CALCULAR"))
        self.btn_agregar_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt;\">AGREGAR</span></p></body></html>"))
        self.btn_agregar_2.setText(_translate("MainWindow", "CALIF:"))
        self.btn_agregar_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">AGREGAR</span></p></body></html>"))
        self.btn_agregar_3.setText(_translate("MainWindow", "PROMEDIO:"))
